### ISSUE TITLE
unauthorized client response from /gdrive-upload endpoint

### ISSUE THREAD

**Issue by gormson** [stephengpope/no-code-architects-toolkit#35]
Hello

First of all thanks for the great work on this materials.

I've just deployed the NCA toolkit, tested it with some endpoints succefully and wanted to try the gdrive-upload one.
I re-deployed the instance to add my personal gdrive account email address using the mentioned key (same address as the cloud plateform account).

when I try the endpoint I've the following error message (500 internal server error) : 
`{
    "build_number": 25,
    "code": 500,
    "endpoint": "/gdrive-upload",
    "id": null,
    "job_id": "870294b9-2f77-4b70-8d9d-631ac43b19d9",
    "message": "('unauthorized_client: Client is unauthorized to retrieve access tokens using this method, or client not authorized for any of the scopes requested.', {'error': 'unauthorized_client', 'error_description': 'Client is unauthorized to retrieve access tokens using this method, or client not authorized for any of the scopes requested.'})",
    "pid": 3,
    "queue_id": 68374467434816,
    "queue_length": 0,
    "queue_time": 0,
    "response": null,
    "run_time": 5.059,
    "total_time": 5.059
}`

I checked the permission from the source file (tested with one from the bucket on the cloud plateform, with one from my personal drive having public access), and the destination folder.

Is there something I'm doing wrong?

Thanks a lot beforehand.

My best.

**Comment by stephengpope** [comment]
you're not doing anything wrong, the gdrive-upload function is a bit specialized and requires some special permissions in your google workspace account that we haven't quite had the chance to document yet. Hopefully soon. Thanks for the feedback and we'll up date it shortly!! much respect for trying it out as is!

**Comment by gormson** [comment]
Thanks for your reply and again thanks for your content!! It's really appreciated !
